formats:
  default: "%prefix% <white>%name%<reset> <gray>» %message%"
  admin: "%prefix% <bold>%name%<reset> <gray>»</gray> <red>%message%"
  owner: "%prefix%<reset> %name%<reset>%suffix%<reset> <gray>»</gray> <rainbow>%message%"

priority: HIGHEST
support_legacy_ampersand: true
debug: false

messages:
  no_permission: "<white>Unknown command."
  reloaded: "<green>Simple Chat Reloaded."