main: not.savage.chat.SimpleChat
authors: [ Savage ]
description: A simple chat plugin for Minecraft.
version: 1.2.1
api-version: 1.21
name: SimpleChat
depend: [ LuckPerms ]
softdepend: [ PlaceholderAPI ]

commands:
  chatreload:
    description: Admin command to interact with SimpleChat